fix image, update fiction

diff --git a/modules/bashx/bashx b/modules/bashx/bashx
--- a/modules/bashx/bashx
+++ b/modules/bashx/bashx
@@ -52,7 +52,8 @@ function @error() {
 }
 
 function _open_heredoc() {
-	if (( ! heredoc_open )); then 
+	if (( ! heredoc_open )); then
+		[[ "${output: -1}" != $'\n' ]] && output+=$'\n'
 		output+=$'cat <<- __eof\n'
 		(( heredoc_open ^= 1 ))
 		(( level == 0 )) && level="${saved_level:=2}"
@@ -60,7 +61,8 @@ function _open_heredoc() {
 }
 
 function _close_heredoc() {
-	if (( heredoc_open )); then 
+	if (( heredoc_open )); then
+		[[ "${output: -1}" != $'\n' ]] && output+=$'\n'
 		output+=$'__eof\n'
 		(( heredoc_open ^= 1 ))
 		saved_level="$level"
@@ -180,6 +182,7 @@ function _render() {
 							output+="$line"$'\n'
 							;;
 						*)
+						_open_heredoc
         				# check if there are special callbacks
           				case "$line" in
 	          				on:*)
@@ -249,6 +252,11 @@ function _render() {
 				output+="${line}"
 			fi
 			;;
+		'{@children}') 
+			_close_heredoc
+			output+=$'{@children}\n'
+			_open_heredoc 
+			;;
 		'{'*'}')
 			output+="$(sed 's|{\([^[:space:]]\+\)}|<a data-bind="\1"></a>|g' <<< "$line")" # "dynamic" variables manageable by setState
 			;;
@@ -314,7 +322,7 @@ eof
 			fi
 			block1="${block1%%\}}"
     		_render "" <<< "${block1/@respond $status \{}"
-    		local newblock="FictionResponseHeaders['content-type']='text/html' FictionResponse['status']='$status'"$'\n{\n'"${render_output}"$'\n} > "$WORKER_OUT"; __fiction_responded=1'
+    		local newblock="FictionResponseHeaders['content-type']='text/html'"$'\n{\n'"${render_output}"$'\n} | fiction.respond '"$status"'; __fiction_responded=1' # > "$WORKER_OUT"; printf "%s\n" "'"$status"'" >"$WORKER_FIFO2"'
 			newblock="${newblock//\&/\\\&}"
   		fi
   		newblock="${newblock##$'\n'}"
@@ -331,10 +339,13 @@ eof
 	unset input out out2 block time block1 render_output
 	#echo "${out1//#NEWLIN#/$'\n'}" 
 	#return
-	if [[ "" ]]; then 
-  		echo "$1:"
-  		echo "${out1//#NEWLIN#/$'\n'}" 
-  		printf "\n"
+	if [[ "$2" ]]; then
+		out1="${out1//\%AND\%/\&}"
+		echo "${out1//#NEWLIN#/$'\n'}" >"$2"
+	elif [[ "" ]]; then
+			echo "$1:"
+  			echo "${out1//#NEWLIN#/$'\n'}" 
+  			printf "\n"
 	else 
   		BASHX_FILENAME="$(readlink -f "$1")"
   		out1="${out1//\%AND\%/\&}"
@@ -386,7 +397,7 @@ function @exclude {
 
 function @require {
   for arg in $@; do 
-    declare -F $arg || echo "Error: required $arg is not found" 
+    declare -F "$arg" || echo "Error: required $arg is not found" 
   done
 }
 
@@ -398,9 +409,9 @@ function @unquote {
 }
 
 function @wrapper() {
-  for key in $@; do 
+  for key in "$@"; do 
     [ -z "$(declare -F "$key")" ] && return
-    eval "$(declare -f "$key" | sed "s+{@children};+}; /${key}() {+g")"
+    eval "$(declare -f "$key" | sed "s+{@children}+}; /${key}() {+g")"
   done
 }
 
@@ -465,12 +476,14 @@ if ! (return 0 2>/dev/null); then
 #elif [[ -z "$BASHX_NESTED" ]]; then
   BASHX_NESTED=true 
   if [ -z "$1" ]; then
-    @error "Invalid usage. Use $0 [filename]"
+    @error "Invalid usage. Use $0 <filename> [output?]"
     exit 1
   elif [ -f "$1" ]; then
-    filename="$1" 
+    filename="$1"
+	[[ "$2" ]] && outputpath="$(readlink -f "$2")"
     [[ "$filename" != "${filename##*/}" ]] && cd "${filename%/*}" && filename="${filename##*/}"
-    bashx "$filename"
+
+    bashx "$filename" "$outputpath"
     exit
   else
     @error "$1 is not found"
